### PR TITLE
Update logging functionality and improve CSS styles for responsiveness

### PR DESCRIPTION
**Pull request by ANUKOOL324**
1. **logger.py**:
   - **Issue**: Redundant file handling when logging messages.
 - **Old Code**: 
  ```
    if not path.exists(log_file):
   with open(log_file, mode="w", encoding="utf-8") as file: 
     file.close() 
   with open(log_file, mode="a", encoding="utf-8") as file:
     file.write(f"{log_msg}\n")
     file.close()
 ```  
       
**When checking if the log file exists, you opened it in write mode (mode="w"), which would create the file if it didn’t exist.** **However, immediately after that, you closed the file without writing anything to it.**
**This is redundant because you don't need to create the file in write mode if you plan to open it again in append mode.**

 - **New Code**: 
 ```
    # Open in append mode; this will create the file if it doesn't exist
      with open(log_file, mode="a", encoding="utf-8") as file: 
          file.write(f"{log_msg}\n")  # This handles both file creation and writing
```

**NOTE:-** The **with** statement opens the file and ensures it’s properly closed when the block of code is exited , eliminating 
                    - **the need for the explicit ```file.close()``` statement.**

 - **Solution**: 
   - Removed unnecessary file close after opening the log file in write mode, utilizing append mode to handle file creation and 
     writing efficiently.

2. **style.css**:
   - **Issues**: 
        - Inconsistent use of units for margin and padding, affecting responsiveness.
        -  Deprecated property value `white-space: nowrap;` in `#noticeText`, which can lead to text overflow issues if the text 
        -  exceeds the container's width.

 - **Solution**:
     - Replaced percentage values for margins and paddings with `rem` units for better scalability and consistency across devices.
     - Removed ````white-space: nowrap;```` from ````#noticeText``` and replaced it with ```white-space: normal```, allowing text to 
        wrap within the container for improved readability and responsiveness.

These changes enhance the logging functionality and improve the CSS styles for better responsiveness and usability across different devices.

### CODE REVIEW

**Review by CoolCat467 — CHANGES_REQUESTED** [review]
One issue, `src/sanescansrv/static/style.css` is auto-generated from `src/sanescansrv/generate_pages.py`, so you will need to change the code that generates the css instead in this case.

**Comment by ANUKOOL324** [comment]
OK i am checking it !

**Comment by ANUKOOL324** [comment]
i am failing in the tests here .. can u help me ? i have applied the changes as per your request ! please assist me here !

**Comment by ANUKOOL324** [comment]
are u working on it ?

**Comment by CoolCat467** [comment]
There is a type issue, one sec

**Comment by ANUKOOL324** [comment]
Thanks  @CoolCat467 ! passed all tests ! 
check my PR and requested changes !
...if any other issue suggest me here !

**Review by CoolCat467 — APPROVED** [review]
Alright, just tested running this with a scanner and it's looking good, thank you so much!

**Pull request merged**
